create table "TABLE_EXAMPLE" (
"ID" VARCHAR(20) NOT NULL,
"NAME" VARCHAR(40) NOT NULL,
"LOCATION" VARCHAR(20) NOT NULL,
"CAPACITY" INT NOT NULL,
CONSTRAINT "TABLE_EXAMPLE_PK" PRIMARY KEY ("ID")
);